BASE_TASK_CONFIG_PATH: habitat_extensions/config/vlnce_task_aug.yaml
SIMULATOR_GPU_ID: 0
TORCH_GPU_ID: 0
NUM_PROCESSES: 1
TENSORBOARD_DIR: data/tensorboard_dirs/cma_pm_aug
CHECKPOINT_FOLDER: data/checkpoints/cma_pm_aug
EVAL_CKPT_PATH_DIR: data/checkpoints/cma_pm_aug

EVAL:
  USE_CKPT_CONFIG: False
  SPLIT: val_unseen
  EPISODE_COUNT: 50000

DAGGER:
  ITERATIONS: 1
  EPOCHS: 12
  UPDATE_SIZE: 157232
  BATCH_SIZE: 5
  P: 1.0
  PRELOAD_LMDB_FEATURES: False
  LMDB_FEATURES_DIR: data/trajectories_dirs/cma_aug/trajectories.lmdb

MODEL:
  INSTRUCTION_ENCODER:
    bidirectional: True

  CMA:
    use: True

  PROGRESS_MONITOR:
    use: True
