BASE_TASK_CONFIG_PATH: habitat_extensions/config/vlnce_task.yaml
SIMULATOR_GPU_ID: 0
TORCH_GPU_ID: 0
NUM_PROCESSES: 1
TENSORBOARD_DIR: data/tensorboard_dirs/seq2seq
CHECKPOINT_FOLDER: data/checkpoints/seq2seq
EVAL_CKPT_PATH_DIR: data/checkpoints/seq2seq

EVAL:
  USE_CKPT_CONFIG: False
  SPLIT: val_unseen
  EPISODE_COUNT: 50000

DAGGER:
  ITERATIONS: 1
  EPOCHS: 15
  UPDATE_SIZE: 10819
  BATCH_SIZE: 5
  P: 1.0
  PRELOAD_LMDB_FEATURES: False
  LMDB_FEATURES_DIR: data/trajectories_dirs/seq2seq/trajectories.lmdb
